### ISSUE TITLE
int too large to convert to C long

### ISSUE THREAD

**Issue by selimcandemirtas** [loodos/zemberek-python#12]
When I import modules in examples.py, I get an error "OverflowError: Python int too large to convert to C long"

Logs:
File "C:\Users\s.demirtas\Anaconda3\envs\transformer\lib\site-packages\zemberek\core\hash\multi_level_mphf.py", line 17, in MultiLevelMphf
    INITIAL_HASH_SEED: np.int32 = np.int32(0x811C9DC5)
OverflowError: Python int too large to convert to C long

The hexadecimal 0x811C9DC5 exceeds the max int32 limit, so I changed it to np.int64 and got this error:
"ValueError: File does not carry expected value in the beginning. magic != LossyIntLookup.magid"

Values when this error occurs:
magic value: -889274641
LossyIntLookup.magid value: 3405692655

How can I solve this? Sorry I'm really unfamiliar with Java and hash coding.

**Comment by harun-loodos** [comment]
Hi, 

I had not tested this version on Windows and apparently some integer values in the Java version are bigger than 32 bit representation and numpy automatically converts it to 32 bit on Mac OS and Linux but not on Windows. I manually changed the values so that every constant value can be represented with 32 bit regardless of the platform. Thanks for the issue.

It should be fixed in #13 and I just released a new version (0.2.2). You can install it again from pip. Closing the issue now.
